@Library('mylibrary')_
pipeline
{
    agent any
    stages
    {
        stage('ContDownload_Master')
        {
            steps
            {
                script
                {
                    cicd.gitDownload("maven")
                }
            }
            
        }
        stage('ContBuild_Master')
        {
            steps
            {
                script
                {
                    cicd.mavenBuild()
                }
            }
        }
        stage('ContDeployment_Master')
        {
            steps
            {
                script
            {
                cicd.tomcatDeploy("DeclarativePipelinewithSharedLibraries","172.31.12.89","testapp")
            }
            }
        }
        stage('ContTesting_Master')
        {
            steps
            {
                script
                {
                    cicd.gitDownload("FunctionalTesting")
                    cicd.runselenium("DeclarativePipelinewithSharedLibraries")
                }
            }
        }
        stage('ContDelivery_Master')
        {
            steps
            {
                script
                {
                    cicd.tomcatDeploy("DeclarativePipelinewithSharedLibraries","172.31.1.221","prodapp")
                }
            }
        }
    }
}

